### ISSUE TITLE
Docs to include non-global usage?

### ISSUE THREAD

**Issue by mweitzel** [saikobee/img-cat#1]
I would love to use this as a component in other tools.

Is this intended to ever be ran not from the terminal, but as a required module by another project?
If so, I would love some docs. If not, would you accept a pull request?

**Comment by wavebeem** [comment]
I just updated the [README](https://github.com/wavebeem/img-cat/blob/master/README.md) showing how to use `img-cat` as a library.

**Comment by wavebeem** [comment]
@mweitzel let me know if that doesn't suffice and I can reopen the issue.
