### ISSUE TITLE
Resize images

### ISSUE THREAD

**Issue by martinheidegger** [saikobee/img-cat#3]
When I try to use img-cat on an image like this:

![npm](https://cloud.githubusercontent.com/assets/914122/10885981/67ca6e06-81c3-11e5-87a1-24d1d0d094ef.png)

in the terminal like:

```
$ img-cat https://www.clever-cloud.com/blog/img/medias/npm.png
```

then the output looks like this:

![screenshot 2015-11-03 00 37 47](https://cloud.githubusercontent.com/assets/914122/10885940/2f419456-81c3-11e5-8a5a-bb9c8279bbc2.png)

in other words the small tiny logo is changed to this huge string. It would be nice to have an option for "pixels per character"

**Comment by wavebeem** [comment]
Wow, I didn't realize that library I was using would load URLs. Neat!

Probably a nearest-neighbor resize to match your terminal dimensions? Any kind of smoothing resize is gonna make edges that don't come out well at very small dimensions.

So maybe an option like `--downscale 2` or `--downscale 3` etc?

**Comment by martinheidegger** [comment]
It is possible to get the width of a terminal. If you use this as 100% then you will need a charPerPixel to fit the image into current terminal at 100%

Thinking of it, maybe something like this might be a good idea

```
--width  Width of the image in characters or % where 100% = width of the base-width (default=size of image or ratio to height, if height is given)
--height Height of the image in rows or % where 100% = height of the base-height (default=size of image or ratio to width, if width is given)
--rowRatio  Floating point number to express the size of 1 pixel in rows (default=1)
--charRatio Floating point number to express the size of 1 pixel in characters (default=1) 
--baseWidth Base width for operation (default=terminal width)
--baseHeight Base height for operation (default=terminal height)
```

**Comment by wavebeem** [comment]
I don't understand the use case for scaling width and height separately.

How about just `--width 80`, and the command line tool grabs the current terminal dimensions by default.

I think that would be easy to understand, and make it so the command produces readable output by default from the command line.

**Comment by martinheidegger** [comment]
Scaling width and height separately follows the same reasoning of layouting images in html. Scaling per height is very useful when layouting images.

**Comment by wavebeem** [comment]
I'm not sure I follow with the comparison to HTML. Can you give me an example of why all of these command line options should be supported?

Here's my reasoning for just having one option: `--width`.
1. Images should not have their aspect ratios distorted.
2. Images should fit in the terminal without line-wrapping.
3. `img-cat` should have sensible defaults for looking at images in the terminal.

**Comment by martinheidegger** [comment]
http://codepen.io/martinheidegger/pen/GpBNvY

**Comment by wavebeem** [comment]
I realize how the width and height attributes of images work, but it still doesn't seem necessary to have independent width and height scale factors. Why would you purposely distort the image?

Also, even if you specified something like "height=50", `img-cat` would still need to check the terminal width and limit it or else you'd get line wrapping.

**Comment by martinheidegger** [comment]
Regarding the height: A page might want to show the image at the header but it should not be bigger than 50% of the screen. I see your point about the possible wrapping of the image to which I would think that a terminal specific "crop" attribute might be good (to crop the image if its wider than x).

I also think that distortion is weird but if `height` is implemented then imho. it would make sense to implement it closely to the html use of it. 

Regarding the defaults: I can those possible defaults:
1. `--crop=terminal-width` in tty mode else no cropping. This way the behavior will be mostly like it is now except that the image will be visible.
2. `--width=100%` this way the image will fit the terminal-width, good because it will always show a big image. Bad because small images will look huge.
3. `--max-width=100%` width of the terminal except when the image is smaller. Improvement over former suggestion but requires the implementation of `max-width`
4. `--width=80` assuming 80 as a good image size in a terminal.

The default of --charRatio should be `1/10` and --rowRatio probably `1/22` (a good approximation if I look at my terminal app default settings).

The `baseWidth` can not be of terminal-width in non-tty mode, in which case I would think that 80 might be a good number.

Regarding the extra attributes for row/charRatio: It is an implementation detail that will need to be dealt with if  height is implemented. Exposing the row/charRatio could make scaling of items easier i.e. The programmer specifies a width & height but allows the charRatio/rowRatio to be set by the user.

**Comment by wavebeem** [comment]
I can understand the hypothetical use case, but I can't understand it in practice. I don't want to needlessly complicate img-cat.

Scaling images before using img-cat tends to look not so great, and it's not really what the tool was designed to do. You really just need an image designed for the terminal size.

If you want to open up a separate issue for a `crop` option, that's a feature I would consider, since I can see it improving the user experience when it defaults to the terminal width.

**Comment by martinheidegger** [comment]
I was looking into img-cat as a tool to add support for images in [msee](https://github.com/firede/msee) I guess I will have to be looking for others.

**Comment by wavebeem** [comment]
Ah, the options make a lot more sense given the context of msee. If you have to end up building the functionality in yourself, know that img-cat really doesn't do much. It's basically just glue code for x256 and get-pixels. https://github.com/wavebeem/img-cat/blob/d73e15b8555739e8286229e26a3ee8f1e8070145/src/img-cat.js#L18-L68
